spring:
  application:
    name: register-center
  profiles: peer2
server:
  port: 9002
eureka:
  instance:
    hostname: peer2
  client:
    registryFetchIntervalSeconds: 5
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://peer1:9001/eureka