spring:
  application:
    name: register-center
  profiles: peer1
server:
  port: 9001
eureka:
  instance:
    hostname: peer1
    prefer-ip-address: false
  client:
    registryFetchIntervalSeconds: 5
    #false 表示不向注册中心中注册自己
    register-with-eureka: true
    #false 表示自己端就是注册中心,我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: true
    serviceUrl:
      defaultZone: http://peer2:9002/eureka
