spring:
  profiles:
    active: peer1
---
spring:
  application:
    name: register-center
  profiles: peer1
server:
  port: 9001
eureka:
  instance:
    hostname: peer1
    prefer-ip-address: false
  client:
    registryFetchIntervalSeconds: 5
    #false 表示不向注册中心中注册自己
    register-with-eureka: true
    #false 表示自己端就是注册中心,我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: true
    serviceUrl:
      defaultZone: http://peer2:9002/eureka
#  server:
    # 关闭保护机制，默认true
#    enable-self-preservation: false
    # 剔除失效服务间隔，默认60000
#    eviction-interval-timer-in-ms: 3000
---
spring:
  application:
    name: register-center
  profiles: peer2
server:
  port: 9002
eureka:
  instance:
    hostname: peer2
  client:
    registryFetchIntervalSeconds: 5
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://peer1:9001/eureka
#  server:
    # 关闭保护机制，默认true
#    enable-self-preservation: false
    # 剔除失效服务间隔，默认60000
#    eviction-interval-timer-in-ms: 3000