eureka:
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://peer1:9001/eureka/
server:
  port: 10001

spring:
  cloud:
    sentinel:
      #取消Sentinel控制台懒加载
      eager: true
      transport:
        #Sentinel 控制台地址
        dashboard: localhost:8080
  application:
    name: consumer
feign:
  sentinel:
    enabled: true
